
name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:          # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Backend
        run: curl -s https://shortify-o6vy.onrender.com/ > /dev/null
